apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db-news/configmap.yaml
  - db-news/pod.yaml
  - db-news/service.yaml
  - server-news/configmap.yaml
  - server-news/pod.yaml
  - server-news/service.yaml