apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels: 
    app: pod-1-label
spec:
  containers:
    - name: pod-1-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html-volume
      configMap:
        name: pod-1-custom-html