apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    app: portal-noticias
spec: 
  containers:
    - name: portal-noticias-container
      image: wesleyfeitosa/portal-noticias:latest
      envFrom:
        - configMapRef:
            name: portal-configmap