apiVersion: v1
kind: Pod
metadata:
  name: db-news-pod
  labels:
    app: db-news-pod
spec:
  containers:
    - name: postgres-db
      image: postgres
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: db-news-configmap