apiVersion: v1
kind: Pod
metadata:
  name: server-news-pod
  labels:
    app: server-news-pod
spec:
  containers:
    - name: server-news-db
      image: wesleyfeitosa/server-news:latest
      ports:
        - containerPort: 3000
      envFrom:
        - configMapRef:
            name: server-news-configmap